name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
    - Package.swift
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
    uses: swiftlang/github-workflows/.github/workflows/swift-test.yml@main
    with:
      swift-version: '6.0'
