name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '6.0.2'
    - name: Test
      run: swift test
