name: CI

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
    - Package.swift
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on macOS
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '6.0'
        
    - name: Show Swift version
      run: swift --version
      
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test --enable-code-coverage
      
    - name: Format Check
      run: |
        if command -v swiftformat &> /dev/null; then
          swiftformat .
          git diff --exit-code
        else
          echo "SwiftFormat not available, skipping format check"
        fi
