name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
    - Package.swift
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
